### ISSUE TITLE
大神，能不能考虑写个three.js ocean的例子

### ISSUE THREAD

**Issue by ryry886** [deyihu/maptalks-three-test#3]
three ocean 
![image](https://user-images.githubusercontent.com/36318585/56946181-02d22300-6b5c-11e9-9e45-9e10bca7ce8a.png)

。。。我自己加进来是下面这样的
![image](https://user-images.githubusercontent.com/36318585/56946143-e46c2780-6b5b-11e9-8f20-dcae4949244e.png)
纹理不对

**Comment by deyihu** [comment]
https://github.com/maptalks/maptalks.three/issues/65
